---

- hosts: localhost
  become: true

  vars:
    result_content: []
    result_attributes: []

  tasks:
    - fail:
        msg: "'first_run' and 'socond_run' must both be defined"
      when: first_run is not defined or second_run is not defined

    - name: Remove '/' from the end of first_run (if exists)
      set_fact:
        first_run: "{{ first_run if first_run[-1] != '/' else first_run[:-1] }}"

    - name: Remove '/' from the end of second_run (if exists)
      set_fact:
        second_run: "{{ second_run if second_run[-1] != '/' else second_run[:-1] }}"

    - name: Get a list of all files in the two given directories
      find:
        paths: "{{ first_run }},{{ second_run }}"
        recurse: yes
      register: files_list

    - name: Keep only the common part of the paths and remove duplicates after that
      set_fact:
        files_list: |
          {% set res = [] -%}
          {% for file in files_list.files -%}
              {% set ignored = res.extend([ file.path[first_run|length+1:] if file.path.startswith(first_run) else file.path[second_run|length+1:] ]) -%}
          {%- endfor %}
          {{ res | unique }}

    - name: Diff the files' attributes
      shell: "diff <( stat -c '%a %U %G %C' {{ '/'.join( [ first_run, item ] ) }} ) <( stat -c '%a %U %G %C' {{ '/'.join( [ second_run, item ] ) }} ); true"
      args:
        executable: /bin/bash
      loop: "{{ files_list }}"
      register: output

    - name: Find attributes difference for each file and store them in result_attributes
      set_fact:
        result_attributes: "{{ result_attributes + [{item.item: item.stdout}] }}"
      loop: "{{ output.results }}"

    - name: Diff the files' contents
      shell: "diff {{ '/'.join( [ first_run, item ] ) }} {{ '/'.join( [ second_run, item ] ) }}; true"
      loop: "{{ files_list }}"
      register: output

    - name: Find content difference for each file and store them in result_content
      set_fact:
        result_content: "{{ result_content + [{item.item: item.stdout}] }}"
      loop: "{{ output.results }}"

    - debug:
        var: result_attributes

    - debug:
        var: result_content

